### ISSUE TITLE
Register View

### ISSUE THREAD

**Issue by OrtizUriel112** [RocioValedoStgo/Spike-Marketplace#3]
1.- El mínimo de caracteres en _username_ no es 8, sino 7.
2.- El caracter especial ** * ** no es tomado en cuenta.

Sucendiendo en el campo _Password_ y _Username_

**Comment by salimvzqz** [comment]
El mínimo de caracteres, ¿haces referencia a la ejecución o requerimiento? @OrtizUriel112

**Comment by Talox1** [comment]
[Issue fixed](https://github.com/RocioValedoStgo/Spike-Marketplace/commit/2531ccdfdce941dcb022e8241095ef11e79cbcfd)
