### ISSUE TITLE
Register View Username

### ISSUE THREAD

**Issue by OrtizUriel112** [RocioValedoStgo/Spike-Marketplace#4]
El campo _Username_ alerta sobre caracteres especiales cuando la entrada son solamente string y no caracteres especiales.
![image](https://user-images.githubusercontent.com/44537097/122625417-a8152180-d06a-11eb-812a-0611bef5d5a8.png)

**Comment by Talox1** [comment]
[Issue fixed](https://github.com/RocioValedoStgo/Spike-Marketplace/commit/2531ccdfdce941dcb022e8241095ef11e79cbcfd)
