### ISSUE TITLE
Register Email

### ISSUE THREAD

**Issue by OrtizUriel112** [RocioValedoStgo/Spike-Marketplace#5]
El Email admite espacios entre caracteres especiales
![image](https://user-images.githubusercontent.com/44537097/122630932-0ce17380-d08d-11eb-89ec-cc12d9a9d18c.png)

**Comment by Talox1** [comment]
[Issue fixed](https://github.com/RocioValedoStgo/Spike-Marketplace/commit/2531ccdfdce941dcb022e8241095ef11e79cbcfd)

**Comment by Talox1** [comment]
[Issue fixed](https://github.com/RocioValedoStgo/Spike-Marketplace/commit/2531ccdfdce941dcb022e8241095ef11e79cbcfd)
